### ISSUE TITLE
Custom Feed image and description.

### ISSUE THREAD

**Issue by Luffyirl** [SkyD666/AniVu#30]
Exactly as the title says . It will be cool to have full access to the looks of ur feed . U also get a bonus Aqua .![1714263656483.jpg](https://github.com/SkyD666/AniVu/assets/128812994/14b02f2f-0552-451f-9099-3e5d7e770024)

**Comment by P0bo** [comment]
Definitely need this feature.No Aqua simp can deny

**Comment by Bubblekey** [comment]
Just found the app , haven't yet added rss feeds yet since there is no opml support. 

Does the app allow adding this custom things ? 
Coz this looks so sick and cool .I have been craving for this feature but sadly no rss app allows that . Only option is to self host but I don't have that much energy to host it. 

Dev please look at this.

**Comment by P0bo** [comment]
The app doesn't yet do this . This is a feature request,this will get added if dev approves it. Hopefully he does 🤗

**Comment by Ripl0gic** [comment]
Finally a recommendation worthy of praise. This would be fire.
